experiment_name: "baseline_mapping_tester"
logging:
  enabled: True
  override_existing: False
  save_dir: "logs"
  verbose: False
wandb:
  enabled: False
  notes: "<TODO - Add notes here>"
  online: True
  project_name: "baseline_mapping_tester"
  verbose: False