experiment_name: "baseline_mapping_tester"
experiment_type: "single_agent"
data:
  dataset_name: "toysim"
  data_dir: "datasets/sa/toysim/npz"
  file_prefix: "results_frame_"
  file_suffix: ".npz"
  world_bounds: [-50, 50, -50, 50] # x_min, x_max, y_min, y_max; meters
logging:
  enabled: True
  override_existing: False
  save_dir: "logs"
  verbose: False
wandb:
  enabled: False
  notes: "<TODO - Add notes here>"
  online: True
  project_name: "baseline_mapping_tester"
  verbose: False